debug: False
bot:
  prefix: "!"
  token: ""
  presences:
    - "リングフィットアドベンチャー"
    - "Apex Legends"
    - "歌枠"
    - "雑談"
    - "マリオカート"

TwitterSyncList:
  - enabled: False
    slug: follows
    credential:
      ck: ""
      cs: ""
      at: ""
      ats: ""

VTuberFanartCrawler:
  enabled: False
  credential:
    ck: ""
    cs: ""
    at: ""
    ats: ""
  gdrive_root_folder_id: ""
  targets:
    - screen_name: "houshoumarine"
      gdrive_folder_name: "宝鐘マリン"
      fanart_hashtag: "マリンのお宝"
      notify_channels:
        - 0000000000000000
