debug: False
bot:
  prefix: "!"
  token: ""
  presences:
    - "雑談"
  event_log_channel: 00000000000000000
TwitterSyncList:
  - enabled: False
    slug: follows
    credential:
      ck: ""
      cs: ""
      at: ""
      ats: ""
    is_sync_follows: True
  - enabled: True
    slug: hololive
    credential:
      ck: ""
      cs: ""
      at: ""
      ats: ""
    is_sync_follows: False
    target_screen_names:
      - hoge
      - foo

VTuberFanartCrawler:
  enabled: False
  credential:
    ck: ""
    cs: ""
    at: ""
    ats: ""
  gdrive_root_folder_id: ""
  targets:
    - screen_name: "houshoumarine"
      gdrive_folder_name: "宝鐘マリン"
      fanart_hashtag: "マリンのお宝"
      notify_channels:
        - 0000000000000000
